# Build and digitally sign the JAR file, then upload it to Maven
name: Build and digitally sign the JAR

on:
  pull_request:
  push:

jobs:
  sign:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo 'hi'
      - name: Process retrieved files
        # here we build everything, then sign and upload to Maven Central, using the nexus-staging plugin
        run: mvn package gpg:sign nexus-staging:deploy nexus-staging:deploy-staged -DskipTests
      - name: Upload resulting artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-sig-hash
          path: target/CmpRaComponent*.*
